git:
  depth: 10
sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '8'
  - '9'
before_install:
  - openssl aes-256-cbc -K $encrypted_f5265da104af_key -iv $encrypted_f5265da104af_iv -in firebase_secret.json.enc -out firebase_secret.json -d
script:
  - npm run lint
  - npm test
