name: Ship js trigger
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          
      - uses: actions/setup-node@v1
        with:
          registry-url: "https://registry.npmjs.org"

      - run: npm ci
      - run: npm run bootstrap
      
      - run: npm run release:trigger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
